---
title: "R Notebook"
output: html_notebook
---
```{r fig.height=10, fig.width=17}


# Get new incidents
open_chart_stats <- get_open_chart_stats()

stopifnot(max(open_chart_stats %>% count(testDate) %>% pull(n))==1)

# output %>% write_rds(here::here("data/open_calls.rds"))
# 
# range(output$testDate)
# range(open_chart_stats$testDate)

open_chart_stats_long <- open_chart_stats %>% select(testDate, `% Open More Than 24 Hours` = Over24Hr_prop,
                  `% Open More Than 4 Days` = Over4D_prop,
                  `% Open More Than 8 Days` = Over8D_prop,
                  `Total % Incomplete Charts` = incomplete30d_prop) %>%
  filter(testDate > min(testDate) + days(30))  %>% pivot_longer(!testDate, names_to="Measure", values_to = "Value") 


open_chart_stats_long$Measure <- factor(open_chart_stats_long$Measure, levels = c("Total % Incomplete Charts",
                                                                                  "% Open More Than 24 Hours",
                                                                                  "% Open More Than 4 Days",
                                                                                  "% Open More Than 8 Days"))

open_chart_stats_long %>% 
  ggplot() + geom_line(aes(x=testDate, y=Value, group=Measure, colour=Measure), size=.8) + ggtitle("Chart Completion performance") +
  theme_light() +
  scale_colour_manual(values=c(
    "% Open More Than 24 Hours" = "firebrick4",
    "% Open More Than 4 Days" = "darkorange3",
    "% Open More Than 8 Days" = "darkolivegreen3",
    "Total % Incomplete Charts" = "gray70"
  )) +
  scale_alpha_manual(values=c(
    "% Open More Than 24 Hours" = 1,
    "% Open More Than 4 Days" = 1,
    "% Open More Than 8 Days" = 1,
    "Total % Incomplete Charts" = .6
  )) +
  scale_y_continuous(breaks=seq(0,1,.01), labels=scales::percent) +
  scale_x_datetime(name="Date", date_breaks="1 year", date_labels="%Y", date_minor_breaks="1 month") +
  theme(legend.position="bottom") +
  guides(colour=guide_legend(title="Measure")) -> p1

open_chart_stats %>% slice_tail(n=1) %>% select(testDate, `% Open More Than 24 Hours` = Over24Hr_prop,
                  `% Open More Than 4 Days` = Over4D_prop,
                  `% Open More Than 8 Days` = Over8D_prop,
                  `Total % Incomplete Charts` = incomplete30d_prop) %>%
  pivot_longer(!testDate, names_to="Measure", values_to = "Value") %>% 
  mutate(Value = paste0(round(Value, 4)*100, "%")) %>% 
  ggplot(aes(x=1, y=4:1)) + 
  geom_text(aes(label=Measure), size=4) + 
  geom_text(aes(label=Value), nudge_y = .3, size=12, fontface="bold") +
  theme_void() + ggtitle("Current Performance") -> p2

library(patchwork)

p1+p2+plot_layout(ncol = 2, widths = c(4,1))
ggsave(here::here("open_calls.pdf"), width=17, height=10, dpi=120)
```
```{r}
class(p1)
length(open_chart_stats)
```

# By Provider
```{r}
# Get data for 12 months
incidents <- import_new_data("2020-07-30", "2021-07-31")
chart_stats <- get_chart_completion_stats(incidents)

```

